### ISSUE TITLE
Lv1. 리뷰 페어 :)

### ISSUE THREAD

**Issue by zidoopal** [rladydqls99/lv1_todolist#1]
1. 컴포넌트 분리
저도 이 부분이 아직도 확실하게 잘 모르겠습니다..😂
같이 이야기 나눠보면 좋을 것 같아요 😭😭
재사용이 가장 많이 일어나는 TodoBox를 잘 나눠 주신 것 같습니다! 

2. input 내용 초기화
+ 작성 이후 input 내용이 초기화 되지 않고 있습니다! 😂
마지막에 useState('') 초기값으로 변경해주는 코드만 추가해주시면 추가하기 버튼 클릭 이후 input창도 초기화 될 수 있을 것 같아요 :) 
[변경 전]
```javascript
 // working에 추가하기 ------------------------
  const clickAddButtonHandler = () => {
    const newInputs = {
      id: inputs.length + 1,
      title: title,
      contents: contents,
      isDone: false,
    };
```
![image](https://github.com/rladydqls99/lv1_todolist/assets/131226548/713174d4-0d7b-405f-9fb5-61027768ead1)

[변경 후]
```javascript
 // working에 추가하기 ------------------------
  const clickAddButtonHandler = () => {
    const newInputs = {
      id: inputs.length + 1,
      title: title,
      contents: contents,
      isDone: false,
    };
    setTitle('');
    setContents('');
```
![image](https://github.com/rladydqls99/lv1_todolist/assets/131226548/7eedf552-b94e-45b2-9cf4-b6fb07e987c8)

마지막에 코드 추가해주시면 추가하기 버튼 클릭 이후 input창도 초기화 될 수 있을 것 같습니다 :) 

3. todo 아이템들이 일정 갯수를 초과하면 Done 부분까지 내용이 초과되는 현상이 보입니다!
App.css에서 .Todo에 height 주셨던 속성을 없애주시면 초과가 되어도 자연스럽게 리스트 부분이 채워지게 될 것 같아요 :)
[변경 전]
```css
.Todo {
  margin-top: 70px;
  height: 300px; 
  display: flex;
  flex-wrap: wrap;
  gap: 20px;
}
```
![image](https://github.com/rladydqls99/lv1_todolist/assets/131226548/599196b4-a949-448c-92cd-405b3bfae3c1)

[변경 후]
```css
.Todo {
  margin-top: 70px;
  /* height: 300px; */
  display: flex;
  flex-wrap: wrap;
  gap: 20px;
}
```
![image](https://github.com/rladydqls99/lv1_todolist/assets/131226548/b7418564-3073-431a-84f6-08a0141dd706)

4. useState도 잘 사용해 주신 것 같습니다 :)

5. 리액트 코드로 작성한 (JSX 관련 코드) JS파일들은 .jsx로 해주셔도 좋을 것 같습니다! 
( 이 부분은 권장사항이라고 한 것 같아서 정답은 아닌 것 같습니다 👼. )

6. README 파일을 잘 정리해주셔서 보기 좋습니다 :)
